export const SPOTIFY_TOKENS = 'SPOTIFY_TOKENS';
export const SPOTIFY_ME_BEGIN = 'SPOTIFY_ME_BEGIN';
export const SPOTIFY_ME_SUCCESS = 'SPOTIFY_ME_SUCCESS';
export const SPOTIFY_ME_FAILURE = 'SPOTIFY_ME_FAILURE';

export const SPOTIFY_TOP_ARTISTS_BEGIN = 'SPOTIFY_TOP_ARTISTS_BEGIN';
export const SPOTIFY_TOP_ARTISTS_SUCCESS = 'SPOTIFY_TOP_ARTISTS_SUCCESS';

export const SPOTIFY_FETCH_ARTIST_BEGIN = 'SPOTIFY_FETCH_ARTIST_BEGIN';
export const SPOTIFY_FETCH_ARTIST_SUCCESS = 'SPOTIFY_FETCH_ARTIST_SUCCESS';
export const SPOTIFY_FETCH_ARTIST_FAILURE = 'SPOTIFY_FETCH_ARTIST_FAILURE';
export const SPOTIFY_FETCH_ARTIST_OPEN = 'SPOTIFY_FETCH_ARTIST_OPEN';
export const SPOTIFY_FETCH_ARTIST_CLOSE = 'SPOTIFY_FETCH_ARTIST_CLOSE';

export const SPOTIFY_CURRENT_TRACK_BEGIN = 'SPOTIFY_CURRENT_TRACK_BEGIN';
export const SPOTIFY_CURRENT_TRACK_SUCCESS = 'SPOTIFY_CURRENT_TRACK_SUCCESS';
