export const SPOTIFY_TOKENS = 'SPOTIFY_TOKENS';
export const SPOTIFY_TOKENS_FAILURE = 'SPOTIFY_TOKENS_FAILURE';

export const SPOTIFY_ME_BEGIN = 'SPOTIFY_ME_BEGIN';
export const SPOTIFY_ME_SUCCESS = 'SPOTIFY_ME_SUCCESS';
export const SPOTIFY_ME_FAILURE = 'SPOTIFY_ME_FAILURE';

export const SPOTIFY_TOP_ARTISTS_BEGIN = 'SPOTIFY_TOP_ARTISTS_BEGIN';
export const SPOTIFY_TOP_ARTISTS_SUCCESS = 'SPOTIFY_TOP_ARTISTS_SUCCESS';
export const SPOTIFY_TOP_ARTISTS_FAILURE = 'SPOTIFY_TOP_ARTISTS_FAILURE';

export const SPOTIFY_TOP_TRACKS_BEGIN = 'SPOTIFY_TOP_TRACKS_BEGIN';
export const SPOTIFY_TOP_TRACKS_SUCCESS = 'SPOTIFY_TOP_TRACKS_SUCCESS';
export const SPOTIFY_TOP_TRACKS_FAILURE = 'SPOTIFY_TOP_TRACKS_FAILURE';

export const SPOTIFY_CURRENT_TRACK_BEGIN = 'SPOTIFY_CURRENT_TRACK_BEGIN';
export const SPOTIFY_CURRENT_TRACK_SUCCESS = 'SPOTIFY_CURRENT_TRACK_SUCCESS';
export const SPOTIFY_CURRENT_TRACK_NOT_PLAYING =
  'SPOTIFY_CURRENT_TRACK_NOT_PLAYING';
export const SPOTIFY_CURRENT_TRACK_FAILURE = 'SPOTIFY_CURRENT_TRACK_FAILURE';

export const SPOTIFY_RECENT_TRACKS_BEGIN = 'SPOTIFY_RECENT_TRACKS_BEGIN';
export const SPOTIFY_RECENT_TRACKS_SUCCESS = 'SPOTIFY_RECENT_TRACKS_SUCCESS';
export const SPOTIFY_RECENT_TRACKS_FAILURE = 'SPOTIFY_RECENT_TRACKS_FAILURE';

export const FETCH_ARTIST_BEGIN = 'FETCH_ARTIST_BEGIN';
export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS';
export const FETCH_ARTIST_FAILURE = 'FETCH_ARTIST_FAILURE';
export const FETCH_ARTIST_OPEN = 'FETCH_ARTIST_OPEN';
export const FETCH_ARTIST_CLOSE = 'FETCH_ARTIST_CLOSE';

export const FETCH_LYRICS_BEGIN = 'FETCH_LYRICS_BEGIN';
export const FETCH_LYRICS_SUCCESS = 'FETCH_LYRICS_SUCCESS';
export const FETCH_LYRICS_FAILURE = 'FETCH_LYRICS_FAILURE';
export const FETCH_LYRICS_OPEN = 'FETCH_LYRICS_OPEN';
export const FETCH_LYRICS_CLOSE = 'FETCH_LYRICS_CLOSE';

export const HIDE_ERROR = 'HIDE_ERROR';
